travis:
  secure:
    BINSTAR_TOKEN: kVB0gDtYrmH8RXIRzKiSpVcly85qPNsKGtyqzMAf3hyiuMmhSRM9k6t1aFmLjf/unNrMXHzoIW8mUZRwMl4Gnng1x9SMvI2qPgjpTT90TGINvZJLWJt00ir5L9qQx7Zg/goLKKTYqI2v8kRVAJO6H6PhCKajP0ntiLNkFO2aho03YlLBlDWpj1dzl1AXN08tjbTum/vtBA2XmQJMgNhZfSpMQMx1dcD/yIUGWGbwnXptqiRIAQSqSd31PUW30vwIJBVXmLtTS6ctUu7K9gIyvpJZQOe1Y+7jewjCBPTnbzgYArczgYjb2cP9KueI+b1218fxA4ooaDcr2zM/FuFFKy7RkQWF9zfntCL+2CVL2L86E9Qt9Ho2GCtRW6SM/I6asf0O85yydC8SvbHPXoqyhFHXsNjQb3Byxb0O0UsZl4NPPWKJuCUxt9XLqWVQcPagoa32ENFfOXX+Qm3VmOiiG1T5JHRBWAOe5Gb3hxv6HlcYyTcMHdxsD8YSWwrIcaAVjcMMhL3VZtmbRCr+Ob3n6R03GSGMwMfVshUgOoJsykw9PZTQseXXDH1GcJWtZKovdOuLZTKYrlsbPTR7bdCKxZFspW7xx03GC8AMzpbhw5dYbIH+ziehYUY4xF52kOjPYmBlEjMOB9xlw/SbMcW2XgoPhOdkZ7OBvhCMd8LIcss=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
